### ISSUE TITLE
Android Studio Hedgehog | 2023.1.1 Canary 13 安装上之后没有文件生成

### ISSUE THREAD

**Issue by xuning2516** [CoXier/LayoutInspectorV2-Pro#5]
Android Studio Hedgehog | 2023.1.1 Canary 13 安装上之后没有文件生成

**Comment by CoXier** [comment]
收到反馈，有时间我看看。

**Comment by jhenninger** [comment]
It would be great to get support for this, especially because Google just released an alpha of [Android Studio for Platform](https://developer.android.com/studio/platform), which is based on Hedgehog.

**Comment by CoXier** [comment]
> It would be great to get support for this, especially because Google just released an alpha of [Android Studio for Platform](https://developer.android.com/studio/platform), which is based on Hedgehog.

Sorry for this issue. As I am very busy on my work recently. I will fix it next month.

**Comment by CoXier** [comment]
@jhenninger @xuning2516 Thanks for your feedback. I fix this crash in LayoutInspectorV2-Pro 1.0.5 which is under review by Jetbrains Plugins Store.

You can update this plugin when LayoutInspectorV2-Pro 1.0.5 is available. (Maybe next week.
